[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.10.2"
tokio = { version = "1.35.0", features = [] }
{% for service in service_names.split(",") %}
{{service.trim()}}_service = { path = "../services/{{service.trim()}}" }
{% endfor %}
