[package]
name = "{{crate_name}}"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.11.0"
tonic-reflection = "0.11.0"
tokio = {{"{"}} version = "1.38.0", features = [] {{"}"}}

{{service_name}}_service = {{"{"}} path = "../services/{{service_name}}" {{"}"}}