name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: server-template
      WORKSPACE: ${{ github.workspace }}/my_workspace
    steps:
      - uses: actions/checkout@v2
      - name: Setup Workspace Directory
        run: |
          mkdir ${{ env.WORKSPACE }}
          echo '[workspace]' >> ${{ env.WORKSPACE }}/Cargo.toml
          echo 'resolver = "2"' >> ${{ env.WORKSPACE }}/Cargo.toml
          echo 'members = ["server", "services/auth"]' >> ${{ env.WORKSPACE }}/Cargo.toml
      - name: Clone Service Template
        run: |
          git clone https://github.com/codeitlikemiley/service_template
      - name: Generate Server
        uses: cargo-generate/cargo-generate-action@v0.18.5
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: "--branch main --define server_name=default --define service_name=auth"
      - name: Move Server
        run: |
          mv ${{ env.PROJECT_NAME }} ${{ runner.temp }}/
          mv ${{ runner.temp }}/${{ env.PROJECT_NAME }} ${{ env.WORKSPACE }}/server
      - name: Generate Auth Service
        uses: cargo-generate/cargo-generate-action@latest
        with:
          name: auth
          template: "./service_template"
          arguments: "--branch main --define service_description=default --define rpc_method=make"
      - name: Move Auth Service
        run: |
          mv /github/workspace/auth ${{ env.WORKSPACE }}/services/auth
      - name: Check Workspace
        run: |
          cd ${{ env.WORKSPACE }}
          cargo check
