name: Build Template
on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ '*' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: server-template
    steps:
    - uses: actions/checkout@v2

    - name: Setup Workspace Directory
      run: |
        mkdir my_workspace
        cd my_workspace
        echo '[workspace]' >> Cargo.toml
        echo 'resolver = "2"' >> Cargo.toml
        echo 'members = ["server", "services/auth"]' >> Cargo.toml

    - name: Generate Server
      uses: cargo-generate/cargo-generate-action@v0.18.5
      with:
        template: https://github.com/your-username/server-template.git
        name: server
        arguments: "--branch main --define server_name=default"

    - name: Generate Auth Service
      uses: cargo-generate/cargo-generate-action@v0.18.5
      with:
        template: https://github.com/codeitlikemiley/service_template.git
        name: auth
        arguments: "--branch main --define service_description=default --define rpc_method=make"

    - name: Build Workspace
      run: |
        cd my_workspace
        cargo check --all
