name: Build Template
on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ '*' ]
    paths-ignore:
      - "**/docs/**"
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: server-template
    steps:
    - uses: actions/checkout@v2
      with:
        path: my_workspace

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install cargo-generate
      run: cargo install cargo-generate

    - name: Setup Workspace Directory
      run: |
        echo '[workspace]' >> my_workspace/Cargo.toml
        echo 'resolver = "2"' >> my_workspace/Cargo.toml
        echo 'members = ["server", "services/auth"]' >> my_workspace/Cargo.toml
        echo 'exclude = ["templates"]' >> my_workspace/Cargo.toml
        mkdir -p my_workspace/services
    - name: Generate Auth Service from Local Template
      run: |
        cd my_workspace/services
        cargo generate --git https://github.com/codeitlikemiley/service_template --name auth --branch main --define service_description=default --define rpc_method=make

    - name: Generate Server
      uses: cargo-generate/cargo-generate-action@v0.18.5
      with:
        name: ${{ env.PROJECT_NAME }}
        arguments: "--branch main --define server_name=default --define service_name=auth"

    - name: Build Workspace
      run: |
        cd my_workspace
        cargo check --all
