name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18 * * 5'
  push:
    branches: [ '*' ]
    paths-ignore:
      - 'docs/**'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME: server-template
    steps:
      - uses: actions/checkout@v2
      - name: Setup Workspace Directory
        run: |
          mkdir my_workspace
          cd my_workspace
          echo '[workspace]' >> Cargo.toml
          echo 'resolver = "2"' >> Cargo.toml
          echo 'members = ["server", "services/auth"]' >> Cargo.toml
      - name: Generate Server
        uses: cargo-generate/cargo-generate-action@v0.18.5
        with:
          name: ${{ env.PROJECT_NAME }}
          arguments: "--branch main --define server_name=default --define service_name=auth"
      - name: Move Server
        run: |
          mv ${{ env.PROJECT_NAME }} ${{ runner.temp }}/
          mv ${{ runner.temp }}/${{ env.PROJECT_NAME }} my_workspace/server
      - name: Generate Auth Service
        uses: cargo-generate/cargo-generate-action@latest
        with:
          name: auth
          template: "https://github.com/codeitlikemiley/service_template"
          arguments: "--branch main --define service_description=default --define rpc_method=make"
      - name: Move Auth Service
        run: |
          mv auth ${{ runner.temp }}/
          mv ${{ runner.temp }}/auth my_workspace/services/auth
      - name: Check Workspace
        run: |
          cd my_workspace
          cargo check